### ISSUE TITLE
Type Checking for Ergo

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#10]
We need a type checker for Ergo and/or the Ergo Calculus. It should be based on the CTOs being imported in the Ergo contracts, it should provide correctness guarantees, it should provide useful information to the editor, it should return useful errors to the Ergo developer.

**Comment by jeromesimeon** [comment]
This requires proper fix to #18

**Comment by jeromesimeon** [comment]
Here are several steps toward getting a full type checker in place for Ergo:
- [x] Import of CTO files as Ergo types (#9)
- [x] Namespace resolution for CTO/Ergo types -- type names have to be resolved to be fully qualified (#18)
- [ ] Namespace resolution for Ergo packages/contracts -- type names in function signatures, etc have to be resolved to be fully qualified (#18)
- [ ] Build type models from CTO types + contract declarations. Those are tables of function signatures organized per contract
- [ ] Implement type checking algorithm for each function with a signature, ensures that the body of that function matches the type signature

Down the road, a proof of a soundness theorem could be attempted: it would guarantee the algorithm is correct and that if the contract passes type checking, then no type error can happen during execution.

**Comment by jeromesimeon** [comment]
Done, released in 0.4.0
