### ISSUE TITLE
Move function inlining code from eval to the compiler

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#275]
Inlining is currently in both the code for eval and in the translation from calculus to NNRC. It should be consolidated in one place, most likely done at the Ergo calculus level.

Some remaining work:
- [x] Add missing parts for the new inlining code (see #309)
- [x] Add function inlining to the compilation path (only hooked in compilation call used in eval)
- [x] Remove inlining from ErgoC -> ErgoNNRC translation
- [x] Make sure inlining works for built-in functions (see also #295)

**Comment by jeromesimeon** [comment]
This should also disentangle the dynamic context from inlining (See #286), at which point the dynamic context can be moved to the corresponding evaluation module.

**Comment by jeromesimeon** [comment]
This is (largely) done in #304 
Some follow up cleanups include:
- [ ] Remove inlining from ErgoC -> ErgoNNRC translaction
- [ ] Make sure inlining works for built-in functions (see also #295)

**Comment by jeromesimeon** [comment]
Work completed in #319
