### ISSUE TITLE
Import for Ergo modules

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#339]
We should allow to import Ergo code (constants, functions, clauses, contracts) from one Ergo file/module to the other.

The propose approach is to use the same `import org.mynamespace.*` approach which is already used for multiple CTO model files.
- [x] Allow import on Ergo modules
- [x] Proper namespace resolution (#18)
- [x] Module import for REPL (#288)
- [x] Module import for native Ergo compiler (`./bin/ergoc.native`)
- [x] Module import for npm `ergoc` and `ergo execute` (See API issue #338)
- [x] Add dependency analysis for Ergo modules so they can be loaded automatically in the right order from Cicero

**Comment by jeromesimeon** [comment]
The propose approach is to use the same `import org.mynamespace.*` approach which is already used for multiple CTO model files.
- [x] Allow import on Ergo modules
- [x] Proper namespace resolution (#18)
- [x] Module import for REPL (#288)
- [x] Module import for native Ergo compiler (`./bin/ergoc.native`)
- [ ] Module import for npm `ergoc` and `ergo execute` (See API issue #338)
- [ ] Add dependency analysis for Ergo module so they can be loaded automatically in the right order from Cicero

**Comment by jeromesimeon** [comment]
Final support in #360 and #361
