### ISSUE TITLE
Full handling for type name hierarchy

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#58]
Type name hierarchy is not yet handled properly. This is relevant for code generation, the reference interpreter, and of course for type checking.

Requires some of the following steps:
- [x] Import of CTO files (See #9)
- [x] Namespace resolution (See #18)
- [x] Uniform handling of CTOs and type declaration in module (done in PR #234)
- [x] Extract type hierarchy from ergo modules after namespace resolution (See #330)
- [x] Pass type hierarchy to backend compiler calls
- [x] Add code-generation for type hierarchy

**Comment by jeromesimeon** [comment]
This also requires proper import of CTO files (See #9 #18).

**Comment by jeromesimeon** [comment]
Finally fixed in PR #501
